Repository didiladi/keptn-generic-job-service, pull requests merged in 2021-05, with the labels that each got.

#16 Rename all service occurences from keptn-generic-job-service to job-executor-service
  .ci_env
  .github/workflows/CI.yml
  .github/workflows/reviewdog.yml
  .gitignore
  Dockerfile
  README.md
  cmd/job-executor-service-initcontainer/main.go
  cmd/job-executor-service/main.go
  deploy/service.yaml
  go.mod
  go.sum
  helm/Chart.yaml
  helm/README.md
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-api-connection.yaml
  helm/values.schema.json
  helm/values.yaml
  initcontainer.Dockerfile
  pkg/config/config.go
  pkg/eventhandler/eventhandlers.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/k8s/job.go
  scripts/build-push-deploy-ks3.sh
  scripts/get-logs.sh
  scripts/port-forward.sh
  skaffold.yaml
  test-events/get-sli.triggered.json
Labels: bug, dependencies, documentation, enhancement, github_actions, go

#17 Extend job configuration to be able to match multiple events for an action
  README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/file/file_test.go
Labels: dependencies, documentation, enhancement, go

#18 Add additional properties of the event accessible for matching
  README.md
  pkg/eventhandler/eventhandler_test.go
  pkg/eventhandler/eventhandlers.go
Labels: enhancement

#19 Match action event names as regex expression
  README.md
  pkg/config/config.go
  pkg/config/config_test.go
Labels: documentation, enhancement, go

#20 Make the location of the initcontainer image configurable
  cmd/job-executor-service/main.go
  deploy/service.yaml
  helm/templates/configmap.yaml
  helm/templates/deployment.yaml
  pkg/eventhandler/eventhandlers.go
  pkg/k8s/job.go
Labels: enhancement

#21 Also build initcontainer.Dockerfile in ci workflow
  .ci_env
  .github/workflows/CI.yml
Labels: github_actions

#22 Add possibility to provide data from incoming cloud events as environment variables in the job
  README.md
  cmd/job-executor-service/main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/eventhandler/eventhandler_test.go
  pkg/eventhandler/eventhandlers.go
  pkg/k8s/job.go
  pkg/k8s/job_test.go
Labels: documentation, enhancement, go

#23 Use golang version 1.16.2
  .github/workflows/CI.yml
  .github/workflows/reviewdog.yml
  Dockerfile
  initcontainer.Dockerfile
Labels: dependencies
